services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  python-server:
    build: ./app
    ports:
      - "8001:8000"
    env_file:
      - config.env
    depends_on:
      - mongodb
